import { loadRazorpayScript, RAZORPAY_KEY_ID } from '../config/razorpay'

/**
 * Initialize Razorpay payment
 * @param {Object} options - Payment options
 * @param {number} options.amount - Amount in paise (INR) or cents (USD)
 * @param {string} options.currency - Currency code (INR, USD, etc.)
 * @param {string} options.name - Customer name
 * @param {string} options.email - Customer email
 * @param {string} options.contact - Customer contact number
 * @param {string} options.description - Payment description
 * @param {Object} options.metadata - Additional metadata
 * @param {Function} options.onSuccess - Success callback
 * @param {Function} options.onFailure - Failure callback
 */
export async function initiateRazorpayPayment({
  amount,
  currency = 'INR',
  name,
  email,
  contact = '',
  description = 'Package Payment',
  metadata = {},
  onSuccess,
  onFailure,
}) {
  try {
    // Load Razorpay script
    const Razorpay = await loadRazorpayScript()

    // Convert amount to paise (smallest currency unit)
    // For INR: amount in rupees * 100
    // For USD: amount in dollars * 100 (cents)
    const amountInPaise = Math.round(amount * 100)

    const options = {
      key: RAZORPAY_KEY_ID,
      amount: amountInPaise,
      currency: currency,
      name: 'Malaysian Trade Net',
      description: description,
      image: '', // Add your logo URL here if needed
      order_id: null, // Will be generated by Razorpay
      handler: function (response) {
        // Payment successful
        if (onSuccess) {
          onSuccess({
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_order_id: response.razorpay_order_id,
            razorpay_signature: response.razorpay_signature,
            ...metadata,
          })
        }
      },
      prefill: {
        name: name || '',
        email: email || '',
        contact: contact || '',
      },
      notes: {
        ...metadata,
      },
      theme: {
        color: '#DC2626', // Primary color
      },
      modal: {
        ondismiss: function () {
          // User closed the payment modal
          if (onFailure) {
            onFailure(new Error('Payment cancelled by user'))
          }
        },
      },
    }

    const razorpay = new Razorpay(options)
    razorpay.on('payment.failed', function (response) {
      // Payment failed
      if (onFailure) {
        onFailure(new Error(response.error.description || 'Payment failed'))
      }
    })

    razorpay.open()
  } catch (error) {
    console.error('Razorpay initialization error:', error)
    if (onFailure) {
      onFailure(error)
    }
  }
}

