import { useState, useEffect } from 'react'
import { useNavigate, useSearchParams, Link } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { useForm } from 'react-hook-form'
import toast from 'react-hot-toast'
import { getRefCodeFromUrl } from '../../utils/helpers'
import { validateName, validateEmail, validatePhone, validatePassword, validateConfirmPassword } from '../../utils/validation'
import { getFunctions, httpsCallable } from 'firebase/functions'
import { doc, getDoc } from 'firebase/firestore'
import { db } from '../../config/firebase'
import { Eye, EyeOff } from 'lucide-react'

export default function AuthPage() {
  const [isLogin, setIsLogin] = useState(true)
  const { signIn, signUp, user, isAdmin } = useAuth()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [validatingRefCode, setValidatingRefCode] = useState(false)
  const [refCodeValid, setRefCodeValid] = useState(null)
  const [refCodeError, setRefCodeError] = useState('')
  
  const urlRefCode = searchParams.get('ref') || getRefCodeFromUrl()
  const [refCode, setRefCode] = useState(urlRefCode || '')

  const { register, handleSubmit, formState: { errors }, watch, setValue } = useForm({
    defaultValues: {
      referralCode: urlRefCode || ''
    }
  })
  
  const password = watch('password')

  useEffect(() => {
    if (user) {
      if (isAdmin) {
        navigate('/admin/dashboard')
      } else {
        navigate('/app/dashboard')
      }
    }
  }, [user, navigate, isAdmin])

  // Validate referral code when it changes
  useEffect(() => {
    if (!isLogin && refCode && refCode.trim().length >= 4) {
      validateReferralCodeExists(refCode)
    } else if (!isLogin && refCode && refCode.trim().length > 0 && refCode.trim().length < 4) {
      setRefCodeValid(false)
      setRefCodeError('Referral code must be at least 4 characters')
    } else if (!isLogin && !refCode) {
      setRefCodeValid(null)
      setRefCodeError('')
    }
  }, [refCode, isLogin])

  const validateReferralCodeExists = async (code) => {
    if (!code || code.trim().length < 4) {
      setRefCodeValid(false)
      setRefCodeError('Invalid referral code')
      return
    }

    setValidatingRefCode(true)
    setRefCodeError('')
    
    try {
      const functions = getFunctions()
      const validateReferralCode = httpsCallable(functions, 'validateReferralCode')
      const result = await validateReferralCode({ refCode: code })
      
      const { valid, error } = result.data
      
      if (valid) {
        setRefCodeValid(true)
        setRefCodeError('')
      } else {
        setRefCodeValid(false)
        setRefCodeError(error || 'Invalid referral code')
      }
    } catch (error) {
      console.error('Error validating referral code:', error)
      setRefCodeValid(false)
      setRefCodeError('Error validating referral code')
    } finally {
      setValidatingRefCode(false)
    }
  }

  const onSubmit = async (data) => {
    try {
      if (isLogin) {
        await signIn(data.email, data.password)
        toast.success('Logged in successfully')
      } else {
        // Validate all fields
        const nameError = validateName(data.name)
        const emailError = validateEmail(data.email)
        const phoneError = validatePhone(data.phone)
        const passwordError = validatePassword(data.password, {
          minLength: 8,
          requireUppercase: true,
          requireNumber: true
        })
        const confirmPasswordError = validateConfirmPassword(data.password, data.confirmPassword)
        
        if (nameError || emailError || phoneError || passwordError || confirmPasswordError) {
          if (nameError) toast.error(nameError)
          if (emailError) toast.error(emailError)
          if (phoneError) toast.error(phoneError)
          if (passwordError) toast.error(passwordError)
          if (confirmPasswordError) toast.error(confirmPasswordError)
          return
        }
        
        // Referral code is optional - only validate if provided
        if (data.referralCode && data.referralCode.trim().length >= 4 && refCodeValid === false) {
          toast.error('Please enter a valid referral code or leave it empty')
          return
        }
        
        const result = await signUp(data.email, data.password, data.name, data.phone, data.referralCode || null)
        toast.success('Account created! Please check your email for verification.')
        
        // Show User ID notification - try to get it from result or wait for it
        let displayedUserId = null
        if (result && result.userId) {
          displayedUserId = result.userId
        } else if (result && result.user) {
          // Wait a bit for userId to be generated by Cloud Function
          setTimeout(async () => {
            try {
              const userDoc = await getDoc(doc(db, 'users', result.user.uid))
              if (userDoc.exists()) {
                const userData = userDoc.data()
                if (userData.userId && userData.userId.startsWith('MTN')) {
                  toast.success(
                    <div className="text-center">
                      <div className="font-bold text-lg mb-1">Your User ID</div>
                      <div className="text-2xl font-mono text-primary">{userData.userId}</div>
                      <div className="text-sm mt-2 text-gray-300">Please save this for future reference</div>
                    </div>,
                    { duration: 8000, icon: '🎉' }
                  )
                }
              }
            } catch (error) {
              console.warn('Could not fetch userId:', error)
            }
          }, 2000)
        }
        
        // Show User ID immediately if available
        if (displayedUserId) {
          setTimeout(() => {
            toast.success(
              <div className="text-center">
                <div className="font-bold text-lg mb-1">Your User ID</div>
                <div className="text-2xl font-mono text-primary">{displayedUserId}</div>
                <div className="text-sm mt-2 text-gray-300">Please save this for future reference</div>
              </div>,
              { duration: 8000, icon: '🎉' }
            )
          }, 1000)
        }
      }
    } catch (error) {
      toast.error(error.message || 'An error occurred')
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-black py-16 px-4 relative overflow-hidden">
      {/* Red glow effect around edges */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-red-500/10 via-transparent to-red-500/10 blur-3xl"></div>
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-red-500/5 rounded-full blur-3xl"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-red-500/5 rounded-full blur-3xl"></div>
      </div>

      <div className="max-w-md w-full relative z-10">
        {/* Logo and Title */}
        <div className="flex items-center gap-4 mb-8 justify-center">
          <div className="w-16 h-16 bg-black rounded-full border-2 border-white flex items-center justify-center flex-shrink-0 overflow-hidden">
            <img 
              src="https://malaysiantrade.net/assets/logo-DRFcCaVQ.png" 
              alt="MTN Logo" 
              className="w-full h-full object-contain p-2"
            />
          </div>
          <div className="text-left">
            <div className="text-white text-sm font-semibold leading-tight">MALAYSIAN</div>
            <div className="text-white text-sm font-semibold leading-tight">TRADE NET</div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex bg-dark-light rounded-t-lg p-1 mb-0 border-b border-gray-800">
          <button
            onClick={() => setIsLogin(true)}
            className={`flex-1 py-3 px-4 rounded-lg font-semibold transition-all ${
              isLogin
                ? 'bg-white text-black'
                : 'text-white hover:text-gray-300'
            }`}
          >
            Login
          </button>
          <button
            onClick={() => setIsLogin(false)}
            className={`flex-1 py-3 px-4 rounded-lg font-semibold transition-all ${
              !isLogin
                ? 'bg-white text-black'
                : 'text-white hover:text-gray-300'
            }`}
          >
            Register
          </button>
        </div>

        {/* Form Card */}
        <div className="bg-dark-light rounded-b-lg p-8 border border-gray-800">
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            {!isLogin && (
              <>
                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Full Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    {...register('name', { 
                      required: 'Name is required',
                      validate: (value) => validateName(value) || true
                    })}
                    className="w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary"
                    placeholder="Enter your full name"
                  />
                  {errors.name && (
                    <p className="text-red-500 text-sm mt-1">{errors.name.message}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Mobile Number <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="tel"
                    {...register('phone', { 
                      required: 'Mobile number is required',
                      validate: (value) => validatePhone(value) || true
                    })}
                    className="w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary"
                    placeholder="10 digit mobile number"
                  />
                  {errors.phone && (
                    <p className="text-red-500 text-sm mt-1">{errors.phone.message}</p>
                  )}
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Referral Code <span className="text-gray-400 text-xs">(Optional)</span>
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      {...register('referralCode', { 
                        onChange: (e) => {
                          const code = e.target.value.toUpperCase().trim()
                          setRefCode(code)
                          setValue('referralCode', code)
                          if (code.length >= 4) {
                            validateReferralCodeExists(code)
                          } else if (code.length === 0) {
                            setRefCodeValid(null)
                            setRefCodeError('')
                          }
                        }
                      })}
                      className={`w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary ${
                        refCodeValid === false ? 'border-red-500' : refCodeValid === true ? 'border-green-500' : ''
                      }`}
                      placeholder="Enter referral code (optional)"
                      disabled={!!urlRefCode}
                    />
                    {validatingRefCode && (
                      <div className="absolute right-3 top-3">
                        <div className="animate-spin rounded-full h-4 w-4 border-t-2 border-b-2 border-primary"></div>
                      </div>
                    )}
                    {refCodeValid === true && !validatingRefCode && (
                      <div className="absolute right-3 top-3 text-green-500">
                        ✓
                      </div>
                    )}
                    {refCodeValid === false && !validatingRefCode && (
                      <div className="absolute right-3 top-3 text-red-500">
                        ✗
                      </div>
                    )}
                  </div>
                  {refCodeError && (
                    <p className="text-red-500 text-sm mt-1">{refCodeError}</p>
                  )}
                </div>
              </>
            )}

            <div>
              <label className="block text-sm font-medium mb-2 text-white">
                {isLogin ? 'User ID' : 'Email'}
              </label>
              <input
                type={isLogin ? 'text' : 'email'}
                {...register('email', { 
                  required: isLogin ? 'User ID is required' : 'Email is required',
                  validate: (value) => {
                    if (isLogin) {
                      // For login, accept email or User ID
                      if (value.includes('@')) {
                        return validateEmail(value) || true
                      } else if (value.toUpperCase().startsWith('MTN')) {
                        return true
                      }
                      return 'Please enter a valid email or User ID (MTNxxxxxx)'
                    } else {
                      // For signup, only accept email
                      return validateEmail(value) || true
                    }
                  }
                })}
                className="w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary"
                placeholder={isLogin ? "Enter your User ID (e.g., MTN329815)" : "Enter your email"}
              />
              {errors.email && (
                <p className="text-red-500 text-sm mt-1">{errors.email.message}</p>
              )}
            </div>

            <div>
              <label className="block text-sm font-medium mb-2 text-white">Password</label>
              <div className="relative">
                <input
                  type={showPassword ? 'text' : 'password'}
                  {...register('password', { 
                    required: 'Password is required',
                    validate: (value) => validatePassword(value, {
                      minLength: 8,
                      requireUppercase: true,
                      requireNumber: true
                    }) || true
                  })}
                  className="w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary pr-10"
                  placeholder="Enter your password"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-3 text-gray-600 hover:text-black"
                >
                  {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                </button>
              </div>
              {errors.password && (
                <p className="text-red-500 text-sm mt-1">{errors.password.message}</p>
              )}
              {!isLogin && (
                <p className="text-gray-400 text-xs mt-1">
                  Must be at least 8 characters with 1 uppercase and 1 number
                </p>
              )}
            </div>

            {!isLogin && (
              <div>
                <label className="block text-sm font-medium mb-2 text-white">Confirm Password</label>
                <div className="relative">
                  <input
                    type={showConfirmPassword ? 'text' : 'password'}
                    {...register('confirmPassword', { 
                      required: 'Please confirm your password',
                      validate: (value) => validateConfirmPassword(password, value) || true
                    })}
                    className="w-full px-4 py-3 bg-white text-black rounded-lg border-0 focus:outline-none focus:ring-2 focus:ring-primary pr-10"
                    placeholder="Confirm your password"
                  />
                  <button
                    type="button"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    className="absolute right-3 top-3 text-gray-600 hover:text-black"
                  >
                    {showConfirmPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                  </button>
                </div>
                {errors.confirmPassword && (
                  <p className="text-red-500 text-sm mt-1">{errors.confirmPassword.message}</p>
                )}
              </div>
            )}

            <button 
              type="submit" 
              className="w-full py-3 px-4 rounded-lg font-semibold text-white bg-gradient-to-r from-orange-500 to-orange-400 hover:from-orange-600 hover:to-orange-500 transition-all shadow-lg"
            >
              {isLogin ? 'Log In' : 'Sign Up'}
            </button>
          </form>

          {isLogin && (
            <div className="mt-4 text-center">
              <Link to="/forgot-password" className="text-white text-sm hover:underline">
                Forgot Your Password?
              </Link>
            </div>
          )}

          <div className="mt-6 text-center">
            <button
              onClick={() => setIsLogin(!isLogin)}
              className="text-white text-sm hover:underline"
            >
              {isLogin ? "Don't have an account? Register" : 'Already have an account? Login'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
